# Generated by Django 4.0 on 2021-12-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='_photo',
            new_name='photo',
        ),
    ]
